import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)

class CodeTemplates:
    """Pre-defined templates for common simple tasks."""
    
    TEMPLATES = {
        'simple_model': '''
# Generated by SpecFlow Template
from django.db import models
from plane.db.models import WorkspaceBaseModel

class {ModelName}(WorkspaceBaseModel):
    """Simple model for {FeatureName}"""
    workspace = models.ForeignKey('db.Workspace', on_delete=models.CASCADE, related_name='{model_name_plural}')
    name = models.CharField(max_length=255, blank=True)
    is_active = models.BooleanField(default=True)
    
    class Meta:
        db_table = '{model_name_lower}'
        ordering = ['-created_at']
    
    def __str__(self):
        return self.name or str(self.id)
''',
        
        'simple_viewset': '''
# Generated by SpecFlow Template
from rest_framework import viewsets
from rest_framework import serializers
from .models import {ModelName}

class {ModelName}Serializer(serializers.ModelSerializer):
    class Meta:
        model = {ModelName}
        fields = ['id', 'name', 'is_active', 'created_at', 'updated_at']

class {ModelName}ViewSet(viewsets.ModelViewSet):
    serializer_class = {ModelName}Serializer
    queryset = {ModelName}.objects.all()
    
    def get_queryset(self):
        return self.queryset.filter(workspace_id=self.request.user.default_workspace_id)
''',
        
        'simple_api': '''
# Generated by SpecFlow Template
from django.urls import path
from .views import {ModelName}ViewSet

urlpatterns = [
    path('{api_name}/', {ModelName}ViewSet.as_view({{'get': 'list', 'post': 'create'}}),),
    path('{api_name}/<uuid:pk>/', {ModelName}ViewSet.as_view({{'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}}),),
]
''',
        
        'simple_component': '''
// Generated by SpecFlow Template
import React from 'react';

export const {ComponentName} = ({{}}) => {{
  return (
    <div className="{component_name_lower}">
      Simple {ComponentName} Component
    </div>
  );
}};
'''
    }
    
    @classmethod
    def get_template(cls, template_type: str, context: Dict[str, Any]) -> str:
        """Get filled template"""
        template = cls.TEMPLATES.get(template_type, '')
        
        if not template:
            logger.warning(f"Template {template_type} not found")
            return ''
        
        # Fill template variables
        model_name = context.get('model_name', 'Item')
        feature_name = context.get('feature_name', 'Feature')
        
        filled = template.format(
            ModelName=model_name,
            FeatureName=feature_name,
            model_name_lower=model_name.lower(),
            model_name_plural=model_name.lower() + 's',
            api_name=context.get('api_name', 'items'),
            ComponentName=model_name,
            component_name_lower=model_name.lower()
        )
        
        return filled
    
    @classmethod
    def is_template_suitable(cls, spec_json: Dict[str, Any]) -> bool:
        """Check if spec can use templates"""
        classification = 'simple'
        
        # Simple specs with clear patterns can use templates
        solution = spec_json.get('solution', '').lower()
        
        template_patterns = ['add', 'create', 'enable', 'flag', 'simple', 'basic']
        return any(pattern in solution for pattern in template_patterns)